name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker build -t django-app .

      - name: Save Docker image to file
        run: |
          docker save django-app | gzip > django-app.tar.gz
  
  test:
      runs-on: ubuntu-latest 
      needs: build
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Load Docker image from file
          run: |
            gunzip -c django-app.tar.gz | docker load
  
        - name: Run tests inside Docker container
          run: |
            docker run --rm django-app python manage.py test
            
  ruff:
      runs-on: ubuntu-latest 
      needs: test
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Load Docker image from file
          run: |
            gunzip -c django-app.tar.gz | docker load
  
        - name: Run ruff-check inside Docker container
          run: |
            docker run --rm django-app ruff .

