name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker build -t django-app .
  
      - name: Run tests inside Docker container
        run: |
          docker run --rm django-app python manage.py test
  
      - name: Run ruff-check inside Docker container
        run: |
          docker run --rm django-app ruff check

